### ISSUE TITLE
Darker than expected textures on almost all crops

### ISSUE THREAD

**Issue by FlashOfAsh** [MehVahdJukaar/FarmersDelightRefabricated#41] opened 2024-04-28 01:55 UTC
### Minecraft version

1.20.1

### Farmer's Delight version

2.0.17

### Fabric Loader version

0.15.7

### Fabric API version

0.92.0+ 1.20.1

### Description

Almost all crops (except tomatoes) have a seemingly darker than usual texture that doesn't fit with most other minecraft crops, including mushrooms

Picture Examples:
Red Mushroom
![image](https://github.com/MehVahdJukaar/FarmersDelight/assets/124220545/35c2a6cb-d8b9-4356-99ff-4c9c11ba97b9)
Brown Mushroom (maybe the least noticeable? at least the light level they give off is right)
![image](https://github.com/MehVahdJukaar/FarmersDelight/assets/124220545/e5c8af84-f771-4288-b886-6ac30a8f2965)
Main Farm picture 1
![image](https://github.com/MehVahdJukaar/FarmersDelight/assets/124220545/9ad04dbc-49e1-49d2-b456-08067e3705f0)
Main Farm picture 2
![image](https://github.com/MehVahdJukaar/FarmersDelight/assets/124220545/be940429-1c64-4836-9d8b-08989cbf3aa9)

### Steps to reproduce

1: Plant crop that isn't tomato (if mushroom wait until it starts becoming a colony)
2: see it

### Mod list

- amendments 1.20-1.1.22
	   \-- mixinsquared 0.1.1
	- appleskin 2.5.1+mc1.20
	   \-- cloth-config 11.0.99
	        \-- cloth-basic-math 0.6.1
	- architectury 9.2.14
	- brainierbees 1.4.3
	- copycats 1.20.1-1.2.6
	- couplings 1.9.5+1.20
	   |-- com_electronwill_night-config_core 3.6.6
	   \-- com_electronwill_night-config_toml 3.6.6
	- create 0.5.1-f-build.1417+mc1.20.1
	   |-- com_google_code_findbugs_jsr305 3.0.2
	   |-- flywheel 0.6.10-2
	   |-- milk 1.2.60
	   |    \-- dripstone_fluid_lib 3.0.2
	   |-- porting_lib_accessors 2.3.2+1.20.1
	   |    \-- porting_lib_core 2.3.2+1.20.1
	   |-- porting_lib_base 2.3.2+1.20.1
	   |    |-- porting_lib_attributes 2.3.2+1.20.1
	   |    |-- porting_lib_common 2.3.2+1.20.1
	   |    |-- porting_lib_core 2.3.2+1.20.1
	   |    |-- porting_lib_fluids 2.3.2+1.20.1
	   |    |-- porting_lib_mixin_extensions 2.3.2+1.20.1
	   |    |-- porting_lib_utility 2.3.2+1.20.1
	   |    \-- reach-entity-attributes 2.4.0
	   |-- porting_lib_brewing 2.3.2+1.20.1
	   |    \-- porting_lib_core 2.3.2+1.20.1
	   |-- porting_lib_client_events 2.3.2+1.20.1
	   |    \-- porting_lib_core 2.3.2+1.20.1
	   |-- porting_lib_entity 2.3.2+1.20.1
	   |    |-- porting_lib_core 2.3.2+1.20.1
	   |    \-- porting_lib_mixin_extensions 2.3.2+1.20.1
	   |-- porting_lib_extensions 2.3.2+1.20.1
	   |    |-- porting_lib_attributes 2.3.2+1.20.1
	   |    |-- porting_lib_common 2.3.2+1.20.1
	   |    |-- porting_lib_core 2.3.2+1.20.1
	   |    \-- reach-entity-attributes 2.4.0
	   |-- porting_lib_models 2.3.2+1.20.1
	   |    |-- porting_lib_core 2.3.2+1.20.1
	   |    |-- porting_lib_fluids 2.3.2+1.20.1
	   |    \-- porting_lib_model_loader 2.3.2+1.20.1
	   |-- porting_lib_networking 2.3.2+1.20.1
	   |    \-- porting_lib_core 2.3.2+1.20.1
	   |-- porting_lib_obj_loader 2.3.2+1.20.1
	   |    |-- porting_lib_core 2.3.2+1.20.1
	   |    \-- porting_lib_model_loader 2.3.2+1.20.1
	   |-- porting_lib_tags 3.0
	   |    \-- porting_lib_core 2.3.2+1.20.1
	   |-- porting_lib_tool_actions 2.3.2+1.20.1
	   |    \-- porting_lib_core 2.3.2+1.20.1
	   |-- porting_lib_transfer 2.3.2+1.20.1
	   |    |-- porting_lib_core 2.3.2+1.20.1
	   |    \-- porting_lib_fluids 2.3.2+1.20.1
	   |-- reach-entity-attributes 2.4.0
	   \-- registrate-fabric 1.3.62-MC1.20.1
	        |-- porting_lib_data 2.1.1090+1.20
	        |    \-- porting_lib_gametest 2.1.1090+1.20
	        \-- porting_lib_model_generators 2.1.1090+1.20
	             |-- porting_lib_gametest 2.1.1090+1.20
	             \-- porting_lib_model_materials 2.1.1090+1.20
	- create_power_loader 1.4.3-mc1.20.1-fabric
	   \-- porting_lib_chunk_loading 2.3.0+1.20.1
	- createoreexcavation 1.4.5
	   \-- chunk-storage-api-fabric 1.0.4
	- creeper_firwork 2.1.0
	- deepslateinstamine 2.5_release
	- disable_enderman_picking_up_blocks 1.2
	- doors-closed 1.0.0+1.19.4
	- dramaticdoors 1.20.1-3.0.2
	- easyanvils 8.0.1
	- easymagic 8.0.1
	- emi 1.1.4+1.20.1+fabric
	- emitrades 1.2.1+mc1.20.1
	   \-- org_quiltmc_parsers_json 0.2.1
	- essential-container 1.0.0
	   \-- essential-loader 1.2.1
	- fabric-api 0.92.0+1.20.1
	   |-- fabric-api-base 0.4.31+1802ada577
	   |-- fabric-api-lookup-api-v1 1.6.36+1802ada577
	   |-- fabric-biome-api-v1 13.0.13+1802ada577
	   |-- fabric-block-api-v1 1.0.11+1802ada577
	   |-- fabric-block-view-api-v2 1.0.1+1802ada577
	   |-- fabric-blockrenderlayer-v1 1.1.41+1802ada577
	   |-- fabric-client-tags-api-v1 1.1.2+1802ada577
	   |-- fabric-command-api-v1 1.2.34+f71b366f77
	   |-- fabric-command-api-v2 2.2.13+1802ada577
	   |-- fabric-commands-v0 0.2.51+df3654b377
	   |-- fabric-containers-v0 0.1.64+df3654b377
	   |-- fabric-content-registries-v0 4.0.11+1802ada577
	   |-- fabric-convention-tags-v1 1.5.5+1802ada577
	   |-- fabric-crash-report-info-v1 0.2.19+1802ada577
	   |-- fabric-data-attachment-api-v1 1.0.0+de0fd6d177
	   |-- fabric-data-generation-api-v1 12.3.4+1802ada577
	   |-- fabric-dimensions-v1 2.1.54+1802ada577
	   |-- fabric-entity-events-v1 1.6.0+1c78457f77
	   |-- fabric-events-interaction-v0 0.6.2+1802ada577
	   |-- fabric-events-lifecycle-v0 0.2.63+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.40+1802ada577
	   |-- fabric-item-api-v1 2.1.28+1802ada577
	   |-- fabric-item-group-api-v1 4.0.12+1802ada577
	   |-- fabric-key-binding-api-v1 1.0.37+1802ada577
	   |-- fabric-keybindings-v0 0.2.35+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.22+1802ada577
	   |-- fabric-loot-api-v2 1.2.1+1802ada577
	   |-- fabric-loot-tables-v1 1.1.45+9e7660c677
	   |-- fabric-message-api-v1 5.1.9+1802ada577
	   |-- fabric-mining-level-api-v1 2.1.50+1802ada577
	   |-- fabric-model-loading-api-v1 1.0.3+1802ada577
	   |-- fabric-models-v0 0.4.2+9386d8a777
	   |-- fabric-networking-api-v1 1.3.11+1802ada577
	   |-- fabric-networking-v0 0.3.51+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.3+1802ada577
	   |-- fabric-particles-v1 1.1.2+1802ada577
	   |-- fabric-recipe-api-v1 1.0.21+1802ada577
	   |-- fabric-registry-sync-v0 2.3.3+1802ada577
	   |-- fabric-renderer-api-v1 3.2.1+1802ada577
	   |-- fabric-renderer-indigo 1.5.1+1802ada577
	   |-- fabric-renderer-registries-v1 3.2.46+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.37+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.28+1802ada577
	   |-- fabric-rendering-v0 1.1.49+df3654b377
	   |-- fabric-rendering-v1 3.0.8+1802ada577
	   |-- fabric-resource-conditions-api-v1 2.3.8+1802ada577
	   |-- fabric-resource-loader-v0 0.11.10+1802ada577
	   |-- fabric-screen-api-v1 2.0.8+1802ada577
	   |-- fabric-screen-handler-api-v1 1.3.30+1802ada577
	   |-- fabric-sound-api-v1 1.0.13+1802ada577
	   |-- fabric-transfer-api-v1 3.3.4+1802ada577
	   \-- fabric-transitive-access-wideners-v1 4.3.1+1802ada577
	- fabric-language-kotlin 1.10.19+kotlin.1.9.23
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.23
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.23.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.3
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.3
	- fabricloader 0.15.7
	   \-- mixinextras 0.3.5
	- farmersdelight 1.20.1-2.0.17+refabricated
	   |-- mm 2.3
	   |-- porting_lib_accessors 2.3.2+1.20.1
	   |    \-- porting_lib_core 2.3.2+1.20.1
	   |-- porting_lib_base 2.3.2+1.20.1
	   |    |-- porting_lib_attributes 2.3.2+1.20.1
	   |    |-- porting_lib_common 2.3.2+1.20.1
	   |    |-- porting_lib_core 2.3.2+1.20.1
	   |    |-- porting_lib_fluids 2.3.2+1.20.1
	   |    |-- porting_lib_mixin_extensions 2.3.2+1.20.1
	   |    |-- porting_lib_utility 2.3.2+1.20.1
	   |    \-- reach-entity-attributes 2.4.0
	   |-- porting_lib_client_events 2.3.2+1.20.1
	   |    \-- porting_lib_core 2.3.2+1.20.1
	   |-- porting_lib_config 2.3.2+1.20.1
	   |    \-- porting_lib_core 2.3.2+1.20.1
	   |-- porting_lib_extensions 2.3.2+1.20.1
	   |    |-- porting_lib_attributes 2.3.2+1.20.1
	   |    |-- porting_lib_common 2.3.2+1.20.1
	   |    |-- porting_lib_core 2.3.2+1.20.1
	   |    \-- reach-entity-attributes 2.4.0
	   |-- porting_lib_lazy_registration 2.3.2+1.20.1
	   |    \-- porting_lib_core 2.3.2+1.20.1
	   |-- porting_lib_loot 2.3.2+1.20.1
	   |    \-- porting_lib_core 2.3.2+1.20.1
	   |-- porting_lib_networking 2.3.2+1.20.1
	   |    \-- porting_lib_core 2.3.2+1.20.1
	   |-- porting_lib_recipe_book_categories 2.3.2+1.20.1
	   |    \-- porting_lib_core 2.3.2+1.20.1
	   |-- porting_lib_registries 2.3.2+1.20.1
	   |    \-- porting_lib_core 2.3.2+1.20.1
	   |-- porting_lib_tags 3.0
	   |    \-- porting_lib_core 2.3.2+1.20.1
	   \-- porting_lib_tool_actions 2.3.2+1.20.1
	        \-- porting_lib_core 2.3.2+1.20.1
	- ferritecore 6.0.0
	- forgeconfigapiport 8.0.0
	- grindenchantments 3.1.2+1.20
	   \-- codec-config-api 1.0.2+1.19.3
	- immersive_armors 1.6.1+1.20.1
	- indium 1.0.30+mc1.20.4
	- iris 1.6.17
	   |-- io_github_douira_glsl-transformer 2.0.0-pre13
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.11.1
	- java 17
	- lithium 0.11.2
	- minecraft 1.20.1
	- mobsonrails 1.0.0
	- modmenu 7.2.2
	- moonlight 1.20-2.11.12
	- morebannerfeatures 1.2.0
	- mr_netherracked 1.0.0
	- nochatreports 1.20.1-v2.2.2
	- nyfsspiders 2.1.1
	- puzzleslib 8.0.24
	- sherdduplication 2.0.5
	- sihywtcamd 1.8+1.20.1
	   |-- cardinal-components-base 5.2.2
	   |-- cardinal-components-entity 5.2.2
	   |-- cardinal-components-item 5.2.2
	   \-- cloth-config 11.0.99
	        \-- cloth-basic-math 0.6.1
	- sliceanddice 3.2.1
	- sodium 0.5.8+mc1.20.1
	- squidnoglitch 1.0.2
	- theprinter 1.4.3+1.20
	   \-- datacriteria 1.0.1+1.20
	- trinkets 3.7.1
	- universal-graves 3.0.0+1.20.1
	   |-- common-protection-api 1.0.0
	   |-- fabric-permissions-api-v0 0.2-SNAPSHOT
	   |-- placeholder-api 2.1.3+1.20.1
	   |-- polymer-core 0.5.15+1.20.1
	   |    |-- polymer-networking 0.5.15+1.20.1
	   |    |    \-- polymer-common 0.5.15+1.20.1
	   |    |         \-- packet_tweaker 0.4.0+1.19.4
	   |    \-- polymer-registry-sync-manipulator 0.5.15+1.20.1
	   |-- polymer-resource-pack 0.5.15+1.20.1
	   |    \-- polymer-common 0.5.15+1.20.1
	   |         \-- packet_tweaker 0.4.0+1.19.4
	   |-- polymer-virtual-entity 0.5.15+1.20.1
	   |    \-- polymer-common 0.5.15+1.20.1
	   |         \-- packet_tweaker 0.4.0+1.19.4
	   |-- predicate-api 0.2.1+1.20.1
	   |-- server_translations_api 2.0.0+1.20
	   |    \-- packet_tweaker 0.4.0+1.19.4
	   \-- sgui 1.2.2+1.20
	- universalenchants 8.0.0
	   \-- extensibleenums 7.0.1
	- xaerominimap 24.0.2
	- xaeroworldmap 1.38.1

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by ChrysanthCow** [comment] 2024-04-28 06:28
Strange, I'll look at the Forge version and see if it's an issue there.

**Comment by ChrysanthCow** [comment] 2024-04-28 20:05
Okay, Forge version has the intended behavior. I'll see what I can do about this.

**Comment by ChrysanthCow** [comment] 2024-04-28 20:09
![image](https://github.com/MehVahdJukaar/FarmersDelight/assets/81167232/369acc07-bab2-44ae-bc45-51b87c546eda)
Hi, I'm unable to reproduce. This is likely an issue caused by another one of your mods.

**Comment by FlashOfAsh** [comment] 2024-04-29 04:19
strange, but i mean, alright, maybe iris or sodium are doing something to it somehow

**Comment by HaXrDEV** [comment] 2024-05-16 18:32
Had the same issue with _Regions Unexplored_, and found out it was caused by _Create Fabric_ due to porting lib overriding the render material. Could very well be related as i see you have _Create Fabric_ in your mod list: https://github.com/Fabricators-of-Create/Create/issues/1259

**Comment by FlashOfAsh** [comment] 2024-05-16 21:08
> Had the same issue with _Regions Unexplored_, and found out it was caused by _Create Fabric_ due to porting lib overriding the render material. Could very well be related as i see you have _Create Fabric_ in your mod list: [Fabricators-of-Create/Create#1259](https://github.com/Fabricators-of-Create/Create/issues/1259)

that does sound very plausible

**Comment by ChrysanthCow** [comment] 2024-06-29 01:32
> Had the same issue with _Regions Unexplored_, and found out it was caused by _Create Fabric_ due to porting lib overriding the render material. Could very well be related as i see you have _Create Fabric_ in your mod list: [Fabricators-of-Create/Create#1259](https://github.com/Fabricators-of-Create/Create/issues/1259)

Porting Lib is also used here, so I'd imagine that this with Iris alone could recreate the issue.

**Comment by ChrysanthCow** [comment] 2024-06-29 01:33
It's apparently fixed on Porting Lib's end, we'll update our included PL modules as soon as we can.

**Comment by MehVahdJukaar** [comment] 2024-08-23 18:02
confirmed that its caused by porting lib. doesnt happen with just FD on since we are not using the module that causes this. Adding stuff like create fabric which includes that module causes this issue. Closing since not our issue

**Closed as completed by MehVahdJukaar** 2024-08-23 18:02 UTC
