### ISSUE TITLE
Axe Crashes

### ISSUE THREAD

**Issue by Halibear** [MehVahdJukaar/FarmersDelightRefabricated#123] opened 2024-12-05 23:34 UTC
### Minecraft version

1.21.1

### Farmer's Delight version

2.2.6

### Fabric Loader version

0.16.9

### Fabric API version

0.110.0

### Description

If I place log block down and try to strip it with axe, game crashes (standard way of creating stripped log)
If I have log in off hand and axe in main hand, and right click cutting board, game crashes
I can place a log on the cutting board then use an axe which provides both the stripped log and the bark successfully.

### Steps to reproduce

Place log
right click with axe

Put log into off hand
Put axe in main hand
right click cutting board

### Mod list

	Fabric Mods: 
		amendments: Amendments 1.21-1.2.19
		anvilrestoration: Anvil Restoration 2.3
		architectury: Architectury 13.0.8
		balm-fabric: Balm 21.0.20
			kuma_api: KumaAPI 21.0.5-SNAPSHOT
		cardinal-components: Cardinal Components API 6.1.1
			cardinal-components-base: Cardinal Components API (base) 6.1.1
			cardinal-components-block: Cardinal Components API (blocks) 6.1.1
			cardinal-components-chunk: Cardinal Components API (chunks) 6.1.1
			cardinal-components-entity: Cardinal Components API (entities) 6.1.1
			cardinal-components-item: Cardinal Components API (items) 6.1.1
			cardinal-components-level: Cardinal Components API (world saves) 6.1.1
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 6.1.1
			cardinal-components-world: Cardinal Components API (worlds) 6.1.1
		carryon: Carry On 2.2.2
		cicada: CICADA 0.9.1+1.21-1.21.1
		cloth-config: Cloth Config v15 15.0.140
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 7.87
		craftingtweaks: Crafting Tweaks 21.1.3
		do_a_barrel_roll: Do a Barrel Roll 3.7.2
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			mixinsquared: MixinSquared 0.1.2-beta.4
		enchanting_reimagined: Enchanting Reimagined 1.1.1
			libgui: LibGui 11.1.0+1.21
				jankson: Jankson 8.0.0+j1.2.3
				libninepatch: LibNinePatch 1.2.0
		endless_music: Endless Music v1.1.0+1.21
		fabric-api: Fabric API 0.110.0+1.21.1
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c19
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.70+b559734419
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.30+be1ed2d719
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a719
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c19
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a719
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8c19
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366f19
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd919
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b319
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.18+b559734419
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.2+7f945d5b19
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.2+e60e56d419
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a719
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.4.0+da19b51a19
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.24+16c4ae2519
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b9919
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.7.0+2122d82819
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.13+ba9dae0619
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd919
			fabric-item-api-v1: Fabric Item API (v1) 11.1.1+d5debaed19
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.6+6823f7cd19
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a719
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b319
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.5.0+01d9a51c19
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.15+3f89f5a519
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.3+3f89f5a519
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c19
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6b19
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.0+c7469b2119
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.1+40875a9319
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c19
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.13+6508971219
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.2.0+34f5d91419
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49c19
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49c19
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b319
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e19
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+1daea21519
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b319
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd019
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b119
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.1+5b5275af19
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.25+8b68f1c719
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.88+b559734419
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c19
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.2+95bead5f19
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.2.0+45b9699719
		fabric-language-kotlin: Fabric Language Kotlin 1.12.3+kotlin.2.0.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.21
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.25.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.9.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.9.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.3
		fabricloader: Fabric Loader 0.16.9
		farmersdelight: Farmer's Delight 1.21.1-2.2.6+refabricated
			mm: Manningham Mills 2.3
			porting_lib_base: Porting Lib Base 3.1.0-beta.47+1.21.1
				porting_lib_accessors: Porting Lib Accessors 3.1.0-beta.47+1.21.1
				porting_lib_asm: Porting Lib ASM 3.1.0-beta.47+1.21.1
				porting_lib_attributes: Porting Lib Attributes 3.1.0-beta.47+1.21.1
				porting_lib_common: Porting Lib Common 3.1.0-beta.47+1.21.1
				porting_lib_entity: Porting Lib Entity 3.1.0-beta.47+1.21.1
				porting_lib_extensions: Porting Lib Extensions 3.1.0-beta.47+1.21.1
				porting_lib_fluids: Porting Lib Fluids 3.1.0-beta.47+1.21.1
				porting_lib_gui_utils: Porting Lib Gui Utils 3.1.0-beta.47+1.21.1
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 3.1.0-beta.47+1.21.1
				porting_lib_tags: Porting Lib Tags 3.0
				porting_lib_transfer: Porting Lib Transfer 3.1.0-beta.47+1.21.1
			porting_lib_config: Porting Lib Config 3.1.0-beta.47+1.21.1
			porting_lib_item_abilities: Porting Lib Item Abilities 3.1.0-beta.47+1.21.1
				mixinextras: MixinExtras 0.5.0-beta.3
				porting_lib_blocks: Porting Lib Blocks 3.1.0-beta.47+1.21.1
				porting_lib_core: Porting Lib Core 3.1.0-beta.47+1.21.1
				porting_lib_gametest: Porting Lib GameTest 3.1.0-beta.47+1.21.1
				porting_lib_level_events: Porting Lib Level Events 3.1.0-beta.47+1.21.1
			porting_lib_lazy_registration: Porting Lib Lazy Register 3.1.0-beta.47+1.21.1
			porting_lib_loot: Porting Lib Loot 3.1.0-beta.47+1.21.1
				porting_lib_conditions: Porting Lib Conditions 3.1.0-beta.47+1.21.1
			porting_lib_recipe_book_categories: Porting Lib Recipe Book Categories 3.1.0-beta.47+1.21.1
		fixedanvilrepaircost: Fixed Anvil Repair Cost 3.4
		forgeconfigapiport: Forge Config API Port 21.1.2
			com_electronwill_night-config_core: core 3.8.0
			com_electronwill_night-config_toml: toml 3.8.0
		inventoryprofilesnext: Inventory Profiles Next 2.1.0
		jamlib: JamLib 1.2.2+1.21.1
			blue_endless_jankson: jankson 1.2.3
		java: Java HotSpot(TM) 64-Bit Server VM 23
		jei: Just Enough Items 19.21.0.247
		libipn: libIPN 6.2.0
		lithostitched: Lithostitched 1.3.8
		minecraft: Minecraft 1.21.1
		modmenu: Mod Menu 11.0.3
			placeholder-api: Placeholder API 2.4.0-pre.2+1.21
		moonlight: Moonlight Lib 1.21-2.17.7
		mr_dungeons_andtaverns: Dungeons and Taverns 1-v4.4.4
		mr_toms_craftableitems: Tom's Craftable Items 1.2.0
		niftycarts: NiftyCarts 21.0.1
		plantsjunk: Plants&Junk 1.0.4-1.21.1
			terraform-wood-api-v1: Terraform Wood API (v1) 11.0.0-alpha.1
		polymorph: Polymorph 1.0.6+1.21.1
		rightclickharvest: Right Click Harvest 4.4.3+1.21.1
		supplementaries: Supplementaries 1.21-3.0.23-beta
		toms_storage: Tom's Simple Storage Mod 2.0.11
		travelersbackpack: Traveler's Backpack 10.1.3
		trinkets: Trinkets 3.10.0
		xaerominimap: Xaero's Minimap 24.6.1
		yet_another_config_lib_v3: YetAnotherConfigLib 3.6.1+1.21-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1

### Logs

[crash-2024-12-05_15.25.16-client.txt](https://github.com/user-attachments/files/18030904/crash-2024-12-05_15.25.16-client.txt)

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by ChrysanthCow** [comment] 2024-12-06 08:08
Duplicate of #122

**Closed as completed by ChrysanthCow** 2024-12-06 08:08 UTC
