### ISSUE TITLE
There are no recipes for a kitchen/cutting board

### ISSUE THREAD

**Issue by RockZe** [MehVahdJukaar/FarmersDelightRefabricated#50] opened 2024-06-05 19:26 UTC
### Minecraft version

1.20.1

### Farmer's Delight version

2.1.1

### Fabric Loader version

0.15.10

### Fabric API version

0.92.1

### Description

I don't know at what point, but after the latest updates, all recipes for slices and parts from whole ingredients broke down, and the food cutting board has no recipes at all

![image](https://github.com/MehVahdJukaar/FarmersDelight/assets/123874691/8413585a-b914-4886-86da-e66ed20cdd8a)

### Steps to reproduce

1. Take a board 
2. Try to slice any product

### Mod list

Loading 426 mods:
	- additional_rpg_jewelry 1.0.2
	   \-- com_github_zsoltmolnarrr_tinyconfig 2.3.2
	- adorn 5.0.1+1.20.1
	- advanced_runtime_resource_pack 0.8.1
	- alloy_forgery 2.1.2+1.20
	- altorigingui 1.0.1
	- ambientenvironment 11.0.0.1
	- ambientsounds 6.0.1
	- amens_origins 2.0.2
	- another_furniture 1.20.1-3.0.1
	- appleskin 2.5.1+mc1.20
	- archers 1.2.1+1.20.1
	- architectury 9.2.14
	- attributefix 21.0.4
	- autotag-convention 2.0.2+1.20
	   \-- autotag 2.0.2+1.20
	- azurelib 2.0.22
	- azurelibarmor 2.0.3
	- backpacked 2.2.7
	- badpackets 0.4.3
	- balm-fabric 7.2.2
	- berserker-rpg 1.0.5
	   \-- com_github_zsoltmolnarrr_tinyconfig 2.3.2
	- betteranimationscollection 8.0.0
	- betterarcheology 1.1.9-1.20.1
	- bettercombat 1.8.5+1.20.1
	- betterdungeons 1.20-Fabric-4.0.4
	   \-- org_reflections_reflections 0.10.2
	- betterf3 7.0.2
	- bettermineshafts 1.20-Fabric-4.0.4
	- bettersmithingtable 1.1.0
	- betterstrongholds 1.20-Fabric-4.0.3
	- biomemusic 1.20.1-2.3
	- bookshelf 20.1.10
	- bosses_of_mass_destruction 1.7.5-1.20.1
	   |-- maelstrom_library 1.6.1-1.20
	   \-- multipart_entities 1.5-1.20
	- bountiful 6.0.3+1.20.1
	- brewinandchewin 3.0.3+1.20.1
	   \-- mm 2.3
	- brutalbosses 1.20.1-6.9
	- cardinal-components 5.2.2
	   |-- cardinal-components-base 5.2.2
	   |-- cardinal-components-block 5.2.2
	   |-- cardinal-components-chunk 5.2.2
	   |-- cardinal-components-entity 5.2.2
	   |-- cardinal-components-item 5.2.2
	   |-- cardinal-components-level 5.2.2
	   |-- cardinal-components-scoreboard 5.2.2
	   \-- cardinal-components-world 5.2.2
	- chatanimation 1.0.5
	- chunksfadein 1.0.5-1.20.1
	   |-- com_moandjiezana_toml_toml4j 0.7.2
	   \-- crowdin-translate 1.4+1.19.3
	- cicada 0.7.1+1.20.1
	- citresewn 1.1.5+1.20.1
	   \-- citresewn-defaults 1.1.5+1.20.1
	- cloth-config 11.1.118
	   \-- cloth-basic-math 0.6.1
	- clumps 12.0.0.4
	- collective 7.60
	- combatroll 1.3.2+1.20.1
	- commonnetworking 1.0.3-1.20.1
	- conjuring 1.0.29+1.20
	   \-- lavender 0.1.0-pre.18+1.20
	        |-- lavender-md 0.1.0-pre.3+1.20
	        \-- lavender-md-owo-ui 0.1.0-pre.3+1.20
	- continuity 3.0.0-beta.5+1.20.1
	- controlling 12.0.2
	- coroutil 1.20.1-1.3.7
	- couplings 1.9.5+1.20
	- craterlib 1.1.1
	- crawl 0.12.0
	   \-- mm 2.3
	- creativecore 2.11.28
	   \-- net_minecraftforge_eventbus 6.0.3
	- creeperoverhaul 3.0.2
	- cristellib 1.1.5
	   \-- blue_endless_jankson 1.2.3
	- ctov 3.4.3
	- cupboard 1.20.1-2.6
	- deathlog 0.3.2+1.20
	- deeperdarker 1.2.6
	   \-- customportalapi 0.0.1-beta64-1.20
	- dehydration 1.3.6
	- detailab 2.6.3+1.20.1-fabric
	- disenchanter 0.1.8+1.20
	- do_a_barrel_roll 3.6.0+1.20.1
	   |-- fabric-permissions-api-v0 0.2-SNAPSHOT
	   \-- mixinsquared 0.1.1
	- dragonloot 1.1.4
	- drippyloadingscreen 2.2.5
	- dummmmmmy 1.20-1.8.17b
	- dungeonz 1.0.4
	- eatinganimationid 1.20+1.9.61
	- effectdescriptions 8.0.2
	- elemental_wizards_rpg 1.1.0
	   \-- com_github_zsoltmolnarrr_tinyconfig 2.3.2
	- emotecraft 2.2.7-b.build.50
	   \-- bendy-lib 4.0.0
	- enchdesc 17.0.15
	- endermanoverhaul 1.0.4
	- endrem 5.2.4
	- enhancedvisuals 1.8.1
	- entityculling 1.6.5
	- environmentz 2.0.8
	   \-- satin 1.13.0
	- epicknightsnmages 0.0.2
	   \-- com_github_zsoltmolnarrr_tinyconfig 2.3.2
	- everycomp 1.20-2.6.55
	   \-- porting_lib_tags 3.0
	- extrakeybinds 0.5.0+1.17-1.19.4
	- extraspellattributes 1.2.2
	- fabric-api 0.92.1+1.20.1
	   |-- fabric-api-base 0.4.31+1802ada577
	   |-- fabric-api-lookup-api-v1 1.6.36+1802ada577
	   |-- fabric-biome-api-v1 13.0.13+1802ada577
	   |-- fabric-block-api-v1 1.0.11+1802ada577
	   |-- fabric-block-view-api-v2 1.0.1+1802ada577
	   |-- fabric-blockrenderlayer-v1 1.1.41+1802ada577
	   |-- fabric-client-tags-api-v1 1.1.2+1802ada577
	   |-- fabric-command-api-v1 1.2.34+f71b366f77
	   |-- fabric-command-api-v2 2.2.13+1802ada577
	   |-- fabric-commands-v0 0.2.51+df3654b377
	   |-- fabric-containers-v0 0.1.64+df3654b377
	   |-- fabric-content-registries-v0 4.0.11+1802ada577
	   |-- fabric-convention-tags-v1 1.5.5+1802ada577
	   |-- fabric-crash-report-info-v1 0.2.19+1802ada577
	   |-- fabric-data-attachment-api-v1 1.0.0+de0fd6d177
	   |-- fabric-data-generation-api-v1 12.3.4+1802ada577
	   |-- fabric-dimensions-v1 2.1.54+1802ada577
	   |-- fabric-entity-events-v1 1.6.0+1c78457f77
	   |-- fabric-events-interaction-v0 0.6.2+1802ada577
	   |-- fabric-events-lifecycle-v0 0.2.63+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.40+1802ada577
	   |-- fabric-item-api-v1 2.1.28+1802ada577
	   |-- fabric-item-group-api-v1 4.0.12+1802ada577
	   |-- fabric-key-binding-api-v1 1.0.37+1802ada577
	   |-- fabric-keybindings-v0 0.2.35+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.22+1802ada577
	   |-- fabric-loot-api-v2 1.2.1+1802ada577
	   |-- fabric-loot-tables-v1 1.1.45+9e7660c677
	   |-- fabric-message-api-v1 5.1.9+1802ada577
	   |-- fabric-mining-level-api-v1 2.1.50+1802ada577
	   |-- fabric-model-loading-api-v1 1.0.3+1802ada577
	   |-- fabric-models-v0 0.4.2+9386d8a777
	   |-- fabric-networking-api-v1 1.3.11+1802ada577
	   |-- fabric-networking-v0 0.3.51+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.3+1802ada577
	   |-- fabric-particles-v1 1.1.2+1802ada577
	   |-- fabric-recipe-api-v1 1.0.21+1802ada577
	   |-- fabric-registry-sync-v0 2.3.3+1802ada577
	   |-- fabric-renderer-api-v1 3.2.1+1802ada577
	   |-- fabric-renderer-indigo 1.5.1+1802ada577
	   |-- fabric-renderer-registries-v1 3.2.46+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.37+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.28+1802ada577
	   |-- fabric-rendering-v0 1.1.49+df3654b377
	   |-- fabric-rendering-v1 3.0.8+1802ada577
	   |-- fabric-resource-conditions-api-v1 2.3.8+1802ada577
	   |-- fabric-resource-loader-v0 0.11.10+1802ada577
	   |-- fabric-screen-api-v1 2.0.8+1802ada577
	   |-- fabric-screen-handler-api-v1 1.3.30+1802ada577
	   |-- fabric-sound-api-v1 1.0.13+1802ada577
	   |-- fabric-transfer-api-v1 3.3.5+8dd72ea377
	   \-- fabric-transitive-access-wideners-v1 4.3.1+1802ada577
	- fabric-language-kotlin 1.11.0+kotlin.2.0.0
	   |-- org_jetbrains_kotlin_kotlin-reflect 2.0.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib 2.0.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 2.0.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 2.0.0
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.24.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.1
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.1
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.6.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.3
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.3
	- fabricloader 0.15.10+local
	   \-- mixinextras 0.3.5
	- fancymenu 2.14.10
	- farmersdelight 1.20.1-2.1.1+refabricated
	   |-- mm 2.3
	   |-- porting_lib_accessors 2.3.4+1.20.1
	   |    \-- porting_lib_core 2.3.4+1.20.1
	   |-- porting_lib_base 2.3.4+1.20.1
	   |    |-- porting_lib_attributes 2.3.4+1.20.1
	   |    |-- porting_lib_common 2.3.4+1.20.1
	   |    |-- porting_lib_core 2.3.4+1.20.1
	   |    |-- porting_lib_entity 2.3.4+1.20.1
	   |    |-- porting_lib_fluids 2.3.4+1.20.1
	   |    |-- porting_lib_mixin_extensions 2.3.4+1.20.1
	   |    |-- porting_lib_transfer 2.3.4+1.20.1
	   |    |-- porting_lib_utility 2.3.4+1.20.1
	   |    \-- reach-entity-attributes 2.4.0
	   |-- porting_lib_client_events 2.3.4+1.20.1
	   |    \-- porting_lib_core 2.3.4+1.20.1
	   |-- porting_lib_config 2.3.4+1.20.1
	   |    \-- porting_lib_core 2.3.4+1.20.1
	   |-- porting_lib_extensions 2.3.4+1.20.1
	   |    |-- porting_lib_attributes 2.3.4+1.20.1
	   |    |-- porting_lib_common 2.3.4+1.20.1
	   |    |-- porting_lib_core 2.3.4+1.20.1
	   |    \-- reach-entity-attributes 2.4.0
	   |-- porting_lib_lazy_registration 2.3.4+1.20.1
	   |    \-- porting_lib_core 2.3.4+1.20.1
	   |-- porting_lib_loot 2.3.4+1.20.1
	   |    \-- porting_lib_core 2.3.4+1.20.1
	   |-- porting_lib_networking 2.3.4+1.20.1
	   |    \-- porting_lib_core 2.3.4+1.20.1
	   |-- porting_lib_recipe_book_categories 2.3.4+1.20.1
	   |    \-- porting_lib_core 2.3.4+1.20.1
	   |-- porting_lib_registries 2.3.4+1.20.1
	   |    \-- porting_lib_core 2.3.4+1.20.1
	   \-- porting_lib_tool_actions 2.3.4+1.20.1
	        \-- porting_lib_core 2.3.4+1.20.1
	- farsight 1.20.1-4.2
	   \-- org_jctools_jctools-core 4.0.1
	- ferritecore 6.0.1
	- feytweaks 1.20-1.2.7
	- fleshz 1.5.1
	- forcemaster-rpg 1.0.5
	   \-- com_github_zsoltmolnarrr_tinyconfig 2.3.2
	- forgeconfigapiport 8.0.0
	- framework 0.6.16
	   \-- org_javassist_javassist 3.29.2-GA
	- friendsandfoes 2.0.10
	- ftblibrary 2001.2.2
	- ftbquests 2001.4.4
	   \-- team_reborn_energy 3.0.0
	- ftbteams 2001.3.0
	- ftbxmodcompat 2.1.1
	- geckolib 4.4.4
	   \-- com_eliotlash_mclib_mclib 20
	- go-fish 1.6.3-1.20.1
	- graveyard 3.0
	- handcrafted 3.0.6
	- hdskinsupport 1.0.0
	- icarus 2.9.0
	- iceberg 1.1.18
	- imbleeding 4.1.1+1.20
	- immediatelyfast 1.2.15+1.20.4
	   \-- net_lenni0451_reflect 1.3.3
	- indium 1.0.30+mc1.20.4
	- infinitemusic 1.6.2
	- inventorysorter 1.9.0-1.20
	   \-- kyrptconfig 1.5.6-1.20
	- invoke 0.2.3
	- iris 1.6.17
	   |-- io_github_douira_glsl-transformer 2.0.0-pre13
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.11.1
	- itemfilters 2001.1.0-build.59
	- java 17
	- jeed 1.20-2.1.12
	- jewelry 1.3.0+1.20.1
	   \-- com_github_zsoltmolnarrr_tinyconfig 2.3.2
	- jobsaddon 1.1.6
	- kambrik 6.1.1+1.20.1
	- konkrete 1.8.1
	- lambdynlights 2.3.2+1.20.1
	   |-- pride 1.2.0+1.19.4
	   \-- spruceui 5.0.0+1.20
	- lazy-language-loader 0.3.3
	- lazydfu 0.1.3
	- leawind_third_person 2.0.8-beta.5
	   \-- mixinextras 0.3.5
	- legendarytooltips 1.4.5
	- levelz 1.4.13
	- libz 1.0.3
	   |-- com_fasterxml_jackson_core_jackson-annotations 2.15.2
	   |-- com_fasterxml_jackson_core_jackson-core 2.15.2
	   \-- com_fasterxml_jackson_core_jackson-databind 2.15.2
	- lithium 0.11.2
	- lithostitched 1.1.5
	- lootr 0.7.33.81
	- lychee 5.1.14
	- mageflame v1.5.0
	- make_bubbles_pop 0.2.0-fabric
	- mca 7.5.18+1.20.1
	- mcwbridges 3.0.0
	- mcwdoors 1.1.0
	- mcwfences 1.1.1
	- mcwfurnitures 3.2.2
	- mcwlights 1.0.6
	- mcwpaths 1.0.5
	- mcwroofs 2.3.0
	- mcwtrpdoors 1.1.3
	- mcwwindows 2.2.1
	- medievalmusic 1.20.1-2.1
	- medievalweapons 1.4.8
	- midnightlib 1.4.1
	- minecells 1.8.2
	   |-- gimm1q 0.5.3
	   \-- omega-config 1.2.3-1.18.1
	- minecraft 1.20.1
	- modernfix 5.17.0+mc1.20.1
	- moonlight 1.20-2.11.30
	- more_rpg_classes 1.1.7-1.20.1
	   \-- com_github_zsoltmolnarrr_tinyconfig 2.3.2
	- morevillagers 5.0.0
	- mousetweaks 2.26
	- mythicmetals 0.19.7+1.20.1
	   |-- additionalentityattributes 1.4.0+1.20.0
	   |-- common-protection-api 1.0.0
	   \-- reach-entity-attributes 2.4.0
	- mythicmobs 1.20.1-fabric-1.4.5
	- mythicmounts 1.20.1-7.4
	- nameplate 1.1.4
	- naturalist 4.0.3
	- nochatreports 1.20.1-v2.2.2
	- notenoughanimations 1.7.3
	- numismatic-overhaul 0.2.14+1.20
	   \-- stacc 1.7.0
	- nutritionz 1.0.6
	- nyfsspiders 2.1.1
	- openpartiesandclaims 0.22.0
	- origins 1.10.0
	   \-- apoli 2.9.0
	        |-- calio 1.11.0
	        \-- playerabilitylib 1.8.0
	- owo 0.11.2+1.20
	- paladins 1.2.0+1.20.1
	- partyaddon 1.0.4
	- patchouli 1.20.1-84-FABRIC
	   \-- fiber 0.23.0-2
	- pehkui 3.8.0+1.14.4-1.20.4
	   \-- kanos_config 0.4.1+1.14.4-1.19.4
	- player-animator 1.0.2-rc1+1.20
	- polymorph 0.49.5+1.20.1
	   \-- spectrelib 0.13.15+1.20.1
	- porting_lib 2.3.4+1.20.1
	   |-- porting_lib_asm 2.3.4+1.20.1
	   |-- porting_lib_attributes 2.3.4+1.20.1
	   |-- porting_lib_blocks 2.3.4+1.20.1
	   |-- porting_lib_brewing 2.3.4+1.20.1
	   |-- porting_lib_chunk_loading 2.3.4+1.20.1
	   |-- porting_lib_common 2.3.4+1.20.1
	   |-- porting_lib_core 2.3.4+1.20.1
	   |-- porting_lib_data 2.3.4+1.20.1
	   |-- porting_lib_entity 2.3.4+1.20.1
	   |-- porting_lib_fluids 2.3.4+1.20.1
	   |-- porting_lib_gametest 2.3.4+1.20.1
	   |-- porting_lib_gui_utils 2.3.4+1.20.1
	   |-- porting_lib_items 2.3.4+1.20.1
	   |-- porting_lib_level_events 2.3.4+1.20.1
	   |-- porting_lib_mixin_extensions 2.3.4+1.20.1
	   |-- porting_lib_model_builders 2.3.4+1.20.1
	   |-- porting_lib_model_generators 2.3.4+1.20.1
	   |-- porting_lib_model_loader 2.3.4+1.20.1
	   |-- porting_lib_model_materials 2.3.4+1.20.1
	   |-- porting_lib_models 2.3.4+1.20.1
	   |-- porting_lib_obj_loader 2.3.4+1.20.1
	   |-- porting_lib_transfer 2.3.4+1.20.1
	   |-- porting_lib_utility 2.3.4+1.20.1
	   \-- reach-entity-attributes 2.4.0
	- presencefootsteps 1.9.4+1.20.1
	   \-- kirin 1.15.6+1.20.1
	- prism 1.0.5
	- projectile_damage 3.2.3+1.20.1
	- puzzleslib 8.1.20
	   \-- puzzlesaccessapi 8.0.7
	- ranged_weapon_api 1.1.1+1.20.1
	- reeses-sodium-options 1.7.2+mc1.20.1-build.101
	- regions_unexplored 0.5.5+1.20.1
	   |-- completeconfig-base 2.5.2
	   \-- completeconfig-gui-cloth 2.5.2
	- rei_custom_command 2.2.0
	- reinfchest 2.4.2+1.20
	   \-- reinfcore 3.1.2+1.20
	- resourcefulconfig 2.1.2
	- resourcefullib 2.1.25
	   |-- com_teamresourceful_bytecodecs 1.0.2
	   \-- com_teamresourceful_yabn 1.0.3
	- resourcepackoverrides 8.0.3
	- roughlyenoughitems 12.1.725
	   \-- error_notifier 1.0.9
	- roughlyenoughprofessions 2.0.2
	- rpgdifficulty 1.3.13
	- runes 0.9.11+1.20.1
	- searchables 1.0.3
	- seriousplayeranimations 1.1.1
	- shield_overhaul 1.0.3
	- sihywtcamd 1.7.5+1.20.1
	- simple-rpc 3.2.4
	   \-- me_hypherionmc_simplerpc_simple-rpc-common 5.0.2
	- simplyswords 1.55.0-1.20.1
	   \-- spruceui 5.0.0+1.20
	- smwyg 1.1.1
	- sodium 0.5.8+mc1.20.1
	- sodium-extra 0.5.4+mc1.20.1-build.115
	   |-- caffeineconfig 1.3.0+1.17
	   \-- crowdin-translate 1.4+1.19.3
	- soulsweapons 1.1.3-1.20-fabric
	- sound_physics_remastered 1.20.1-1.4.2
	- spark 1.10.53
	- spell_engine 0.14.3+1.20.1
	- spell_power 0.10.2+1.20.1
	   \-- com_github_zsoltmolnarrr_tinyconfig 2.3.2
	- spellbladenext 1.14.0
	- spoornbountymobs 4.0-1.20.1
	   \-- org_apache_commons_commons-math3 3.3
	- stack-to-nearby-chests 0.5.7
	   \-- libgui 8.0.2+1.20
	        |-- jankson 6.0.0+j1.2.3
	        \-- libninepatch 1.2.0
	- stackablepotions 1.0.0
	- status-effect-bars 1.0.3
	- structure_pool_api 1.0+1.20.1
	- styled-nicknames 1.2.1+1.20
	   |-- fabric-permissions-api-v0 0.2-SNAPSHOT
	   \-- player-data-api 0.2.2+1.19.3
	- styledchat 2.2.3+1.20.1
	   |-- fabric-permissions-api-v0 0.2-SNAPSHOT
	   |-- placeholder-api 2.1.3+1.20.1
	   \-- player-data-api 0.2.2+1.19.3
	- styledplayerlist 3.1.1+1.20.1
	   \-- player-data-api 0.2.2+1.19.3
	- taterzens 1.11.7
	   |-- config2brigadier 1.2.6
	   \-- sgui 1.2.2+1.20
	- terrablender 3.0.1.6
	   |-- com_electronwill_night-config_core 3.6.7
	   \-- com_electronwill_night-config_toml 3.6.7
	- tiered 1.3.3
	   \-- reach-entity-attributes 2.4.0
	- tooltipfix 1.1.1-1.20
	- trashslot 15.1.0
	- travelerstitles 1.20-Fabric-4.0.2
	- treechop 0.19.0
	- trinkets 3.7.2
	- true-darkness-fork 1.0.2-1.20.x
	- twigs 3.1.0
	- universal-graves 3.0.1+1.20.1
	   |-- common-protection-api 1.0.0
	   |-- fabric-permissions-api-v0 0.2-SNAPSHOT
	   |-- placeholder-api 2.1.3+1.20.1
	   |-- polymer-core 0.5.19+1.20.1
	   |    |-- polymer-networking 0.5.19+1.20.1
	   |    |    \-- polymer-common 0.5.19+1.20.1
	   |    |         \-- packet_tweaker 0.4.0+1.19.4
	   |    \-- polymer-registry-sync-manipulator 0.5.19+1.20.1
	   |-- polymer-resource-pack 0.5.19+1.20.1
	   |    \-- polymer-common 0.5.19+1.20.1
	   |         \-- packet_tweaker 0.4.0+1.19.4
	   |-- polymer-virtual-entity 0.5.19+1.20.1
	   |    \-- polymer-common 0.5.19+1.20.1
	   |         \-- packet_tweaker 0.4.0+1.19.4
	   |-- predicate-api 0.2.1+1.20.1
	   |-- server_translations_api 2.0.0+1.20
	   |    \-- packet_tweaker 0.4.0+1.19.4
	   \-- sgui 1.2.2+1.20
	- unremovableeffects 1.0.0+1.20
	- villagerquests 1.1.2
	- visuality 0.7.1+1.20
	- voicechat 1.20.1-2.5.15
	- watut 1.20.1-1.1.1
	- waystones 14.1.3
	- whats_that_slot 1.3.4+1.20.1
	- witcher-rpg 1.0.6
	   \-- com_github_zsoltmolnarrr_tinyconfig 2.3.2
	- wizards 1.2.0+1.20.1
	- wthit 8.11.0
	- xaerominimap 24.1.1
	- xaeroworldmap 1.38.4
	- yeetusexperimentus 2.3.1-build.6+mc1.20.1
	- yet_another_config_lib_v3 3.4.2+1.20.1-fabric
	   |-- com_twelvemonkeys_common_common-image 3.10.0
	   |-- com_twelvemonkeys_common_common-io 3.10.0
	   |-- com_twelvemonkeys_common_common-lang 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-core 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-metadata 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-webp 3.10.0
	   |-- org_quiltmc_parsers_gson 0.2.1
	   \-- org_quiltmc_parsers_json 0.2.1
	- yungsapi 1.20-Fabric-4.0.5
	   \-- mixinextras 0.3.5

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by MehVahdJukaar** [comment] 2024-06-09 08:01
try with no other mod on

**Comment by RockZe** [comment] 2024-06-09 18:47
> try with no other mod on

Okay, really, everything is fine without other mods, but I don't want to give up other mods. Is there a list of incompatible mods? I haven't been able to find the culprit for 2 hours...

**Comment by MehVahdJukaar** [comment] 2024-06-10 00:42
Such list can't exist. Suppose they did then I would immediately fix the incompatibility making the list empty

**Comment by unilock** [comment] 2024-06-19 14:42
I'm having what's probably the same issue with the Cooking Pot `RecipeSerializer` not being recognized in recipe JSONs for some reason.

<details>
<summary>These are the mods we have in common (as reported by Loader):</summary>

```
additionalentityattributes
advanced_runtime_resource_pack
alloy_forgery
appleskin
architectury
attributefix
autotag
autotag-convention
badpackets
balm-fabric
betterdungeons
bettersmithingtable
blue_endless_jankson
brewinandchewin
cardinal-components
cardinal-components-base
cardinal-components-block
cardinal-components-chunk
cardinal-components-entity
cardinal-components-item
cardinal-components-level
cardinal-components-scoreboard
cardinal-components-world
cloth-basic-math
cloth-config
clumps
com_electronwill_night-config_core
com_electronwill_night-config_toml
com_eliotlash_mclib_mclib
com_moandjiezana_toml_toml4j
commonnetworking
common-protection-api
com_teamresourceful_bytecodecs
com_teamresourceful_yabn
com_twelvemonkeys_common_common-image
com_twelvemonkeys_common_common-io
com_twelvemonkeys_common_common-lang
com_twelvemonkeys_imageio_imageio-core
com_twelvemonkeys_imageio_imageio-metadata
com_twelvemonkeys_imageio_imageio-webp
conjuring
couplings
crowdin-translate
cupboard
deathlog
fabric-permissions-api-v0
farmersdelight
ferritecore
fiber
forgeconfigapiport
geckolib
go-fish
handcrafted
icarus
indium
jankson
java
kanos_config
lambdynlights
lavender
lavender-md
lavender-md-owo-ui
libgui
libninepatch
lithium
lootr
midnightlib
minecraft
mixinextras
mixinsquared
mm
modernfix
mousetweaks
mythicmetals
notenoughanimations
omega-config
openpartiesandclaims
org_javassist_javassist
org_jetbrains_kotlin_kotlin-reflect
org_jetbrains_kotlin_kotlin-stdlib
org_jetbrains_kotlin_kotlin-stdlib-jdk7
org_jetbrains_kotlin_kotlin-stdlib-jdk8
org_jetbrains_kotlinx_atomicfu-jvm
org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm
org_jetbrains_kotlinx_kotlinx-coroutines-jdk8
org_jetbrains_kotlinx_kotlinx-datetime-jvm
org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm
org_jetbrains_kotlinx_kotlinx-serialization-core-jvm
org_jetbrains_kotlinx_kotlinx-serialization-json-jvm
org_quiltmc_parsers_gson
org_quiltmc_parsers_json
org_reflections_reflections
owo
packet_tweaker
patchouli
pehkui
placeholder-api
playerabilitylib
player-data-api
polymer-common
polymer-core
polymer-networking
polymer-registry-sync-manipulator
polymer-resource-pack
polymer-virtual-entity
polymorph
porting_lib
porting_lib_accessors
porting_lib_asm
porting_lib_attributes
porting_lib_base
porting_lib_blocks
porting_lib_brewing
porting_lib_chunk_loading
porting_lib_client_events
porting_lib_common
porting_lib_config
porting_lib_core
porting_lib_data
porting_lib_entity
porting_lib_extensions
porting_lib_fluids
porting_lib_gametest
porting_lib_gui_utils
porting_lib_items
porting_lib_lazy_registration
porting_lib_level_events
porting_lib_loot
porting_lib_mixin_extensions
porting_lib_model_builders
porting_lib_model_generators
porting_lib_model_loader
porting_lib_model_materials
porting_lib_models
porting_lib_networking
porting_lib_obj_loader
porting_lib_recipe_book_categories
porting_lib_registries
porting_lib_tags
porting_lib_tool_actions
porting_lib_transfer
porting_lib_utility
predicate-api
pride
ranged_weapon_api
reach-entity-attributes
reeses-sodium-options
resourcefulconfig
resourcefullib
resourcepackoverrides
satin
server_translations_api
sgui
sodium
spark
spectrelib
spruceui
styledchat
styled-nicknames
styledplayerlist
team_reborn_energy
terrablender
tooltipfix
trashslot
trinkets
twigs
visuality
wthit
xaerominimap
xaeroworldmap
yet_another_config_lib_v3
yungsapi
```
</details>

I'll start working on narrowing it down.

EDIT: Nevermind, my issue is unrelated. Sorry for the false alarm!

**Comment by MehVahdJukaar** [comment] 2024-07-26 13:57
i think this was caused by item obliterator and has since been fixed on their end

**Closed as completed by MehVahdJukaar** 2024-07-26 13:57 UTC
