### ISSUE TITLE
Ticking Entity Crash Tomato Vines (?)

### ISSUE THREAD

**Issue by Cr4fTJuNkiE** [MehVahdJukaar/FarmersDelightRefabricated#120] opened 2024-12-03 23:02 UTC
### Minecraft version

1.21.1

### Farmer's Delight version

2.2.4

### Fabric Loader version

0.16.9-1.21.1

### Fabric API version

0.110.0+1.21.1

### Description

Game Crashed while playing.

### Steps to reproduce

Just playing the game. 

### Mod list

Fabric Mods: 
		additionallanterns: Additional Lanterns 1.1.1
		additionalstructures: Additional Structures 5.0.1-fabric
		advanced_reborn: Advanced Reborn 1.3.2
		advancednetherite: Advanced Netherite 2.2.0-1.21.1
		allarrowsinfinityfix: All Arrows Infinity Fix 1.7.2
		alloy_forgery: Alloy Forgery 2.4.1+1.21
		ambientenvironment: AmbientEnvironment 18.0.0.2
		ambientsounds: AmbientSounds 6.1.3
		animal_feeding_trough: Animal Feeding Trough 1.1.2+1.21.1
		appleskin: AppleSkin 3.0.5+mc1.21
		architectury: Architectury 13.0.8
		armor_hud: Armor Hud 2.1
		artifacts: Artifacts 12.0.6
			com_electronwill_night-config_core: core 3.8.0
			com_electronwill_night-config_toml: toml 3.8.0
			expandability: ExpandAbility 12.0.0
		attributefix: AttributeFix 21.1.2
		badpackets: Bad Packets 0.8.1
		betteradvancements: Better Advancements 0.4.3.21
		betterdeserttemples: YUNG's Better Desert Temples 1.21.1-Fabric-4.1.2
		betterdungeons: YUNG's Better Dungeons 1.21.1-Fabric-5.1.4
		betterfortresses: YUNG's Better Nether Fortresses 1.21.1-Fabric-3.1.3
		bettergrass: BetterGrassify 1.3.4+fabric.1.21.1
		betterjungletemples: YUNG's Better Jungle Temples 1.21.1-Fabric-3.1.2
		bettermineshafts: YUNG's Better Mineshafts 1.21.1-Fabric-5.1.1
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.21.1-Fabric-4.1.2
		betterstrongholds: YUNG's Better Strongholds 1.21.1-Fabric-5.1.2
		betterwitchhuts: YUNG's Better Witch Huts 1.21.1-Fabric-4.1.1
		bladesdungeons: Blade's Dungeons. 1.0.2
		bookshelf: Bookshelf 21.1.13
		bushierflowers: Bushier Flowers 0.0.3-1.21
		c2me: Concurrent Chunk Management Engine 0.3.0+alpha.0.299+1.21.1
			c2me-base: Concurrent Chunk Management Engine (Base) 0.3.0+alpha.0.299+1.21.1
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.3.0+alpha.0.299+1.21.1
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.3.0+alpha.0.299+1.21.1
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.3.0+alpha.0.299+1.21.1
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.3.0+alpha.0.299+1.21.1
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.3.0+alpha.0.299+1.21.1
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.3.0+alpha.0.299+1.21.1
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.3.0+alpha.0.299+1.21.1
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.3.0+alpha.0.299+1.21.1
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.3.0+alpha.0.299+1.21.1
			c2me-opts-dfc: Concurrent Chunk Management Engine (Optimizations/Density Function Compiler) 0.3.0+alpha.0.299+1.21.1
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.3.0+alpha.0.299+1.21.1
			c2me-opts-natives-math: Concurrent Chunk Management Engine (Optimizations/Natives Math) 0.3.0+alpha.0.299+1.21.1
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.3.0+alpha.0.299+1.21.1
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.3.0+alpha.0.299+1.21.1
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.3.0+alpha.0.299+1.21.1
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.3.0+alpha.0.299+1.21.1
			c2me-rewrites-chunk-system: Concurrent Chunk Management Engine (Rewrites/Chunk System) 0.3.0+alpha.0.299+1.21.1
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.3.0+alpha.0.299+1.21.1
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.3.0+alpha.0.299+1.21.1
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.3.0+alpha.0.299+1.21.1
			com_ibm_async_asyncutil: asyncutil 0.1.0
			io_reactivex_rxjava3_rxjava: rxjava 3.1.8
			net_objecthunter_exp4j: exp4j 0.4.8
			org_jctools_jctools-core: jctools-core 4.0.5
			org_reactivestreams_reactive-streams: reactive-streams 1.0.4
		cardinal-components: Cardinal Components API 6.1.1
			cardinal-components-base: Cardinal Components API (base) 6.1.1
			cardinal-components-block: Cardinal Components API (blocks) 6.1.1
			cardinal-components-chunk: Cardinal Components API (chunks) 6.1.1
			cardinal-components-entity: Cardinal Components API (entities) 6.1.1
			cardinal-components-item: Cardinal Components API (items) 6.1.1
			cardinal-components-level: Cardinal Components API (world saves) 6.1.1
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 6.1.1
			cardinal-components-world: Cardinal Components API (worlds) 6.1.1
		carryon: Carry On 2.2.2
		chalk: Chalk 2.2.5+1.21.1
			com_github_mclegoman_releasetypeutils: releasetypeutils 2.1.0
			fabric-simplelibs: Simple Fabric Libs 2.0.0
		citresewn: CIT Resewn 1.2.1+1.21
			citresewn-defaults: CIT Resewn: Defaults 1.2.1+1.21
		cloth-config: Cloth Config v15 15.0.140
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 19.0.0.1
		comforts: Comforts 9.0.2+1.21.1
			spectrelib: SpectreLib 0.17.2+1.21
		continuity: Continuity 3.0.0-beta.5+1.21
		copperhopper: Copper Hopper 0.10.0+1.21.1
		cottages: Cottages 1.0.1
		creativecore: CreativeCore 2.12.23
			net_neoforged_bus: bus 7.2.0
		cropsloverain: Crops Love Rain 2.1.1
		ctov: ChoiceTheorem's Overhauled Village 3.5.4
		cutthrough: Cut Through 21.1.0
		deco_storage: Decorative Storage 2.311-beta-1.21.1-fabric
		distanthorizons: Distant Horizons 2.2.1-a
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c90
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a790
		easymagic: Easy Magic 21.1.0
		eatinganimationid: Eating Animation 1.21+1.9.72
		echochest: Echo Chest 21.1.0
		eldritch_mobs: EldritchMobs 1.16.3
			polymer-blocks: Polymer (Textured Blocks) 0.9.9+1.21
			polymer-core: Polymer (Core) 0.9.9+1.21
				polymer-networking: Polymer (Networking) 0.9.9+1.21
					polymer-common: Polymer (Common) 0.9.9+1.21
						packet_tweaker: Packet Tweaker 0.5.5+1.21
				polymer-registry-sync-manipulator: Polymer (Registry Sync Manipulator) 0.9.9+1.21
			server_translations_api: Server Translations API 2.3.1+1.21-pre2
		emerald_tools: Emerald Tools 1.8.17
			blue_endless_jankson: jankson 1.2.3
			pugh_tools: Pugh Tools 1.8.19
		enchdesc: EnchantmentDescriptions 21.1.5
		enhancedblockentities: Enhanced Block Entities 0.10.2+1.21
		entity_model_features: Entity Model Features 2.2.6
		entity_sound_features: Entity Sound Features 0.4
		entity_texture_features: Entity Texture Features 6.2.8
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling 1.7.0
		everycomp: Every Compat 1.21-2.7.5
		fabric-api: Fabric API 0.110.0+1.21.1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.70+b559734419
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.30+be1ed2d719
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a719
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c19
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a719
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8c19
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366f19
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd919
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b319
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.18+b559734419
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.2+7f945d5b19
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.2+e60e56d419
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a719
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.4.0+da19b51a19
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.24+16c4ae2519
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b9919
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.7.0+2122d82819
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.13+ba9dae0619
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd919
			fabric-item-api-v1: Fabric Item API (v1) 11.1.1+d5debaed19
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.6+6823f7cd19
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b319
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.5.0+01d9a51c19
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.15+3f89f5a519
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.3+3f89f5a519
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c19
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6b19
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.0+c7469b2119
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.1+40875a9319
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c19
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.13+6508971219
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.2.0+34f5d91419
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49c19
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49c19
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b319
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e19
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+1daea21519
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b319
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd019
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b119
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.1+5b5275af19
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.25+8b68f1c719
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.88+b559734419
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c19
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.2+95bead5f19
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.2.0+45b9699719
		fabrication: Fabrication 3.5.2+1.21
			lib39-deferral: Lib39 (Deferral) 1.5.0-experimental6.1+1.20.1
		fabricloader: Fabric Loader 0.16.9
		fabricshieldlib: Fabric Shield Lib 1.7.2-1.21.1
			mm: Manningham Mills 2.3
		fabricskyboxes: FabricSkyBoxes 0.7.4+mc1.21
		fallingleaves: Falling Leaves 1.16.4
		fallingtree: FallingTree 1.21.1.2
		farmersdelight: Farmer's Delight 1.21.1-2.2.4+refabricated
			porting_lib_accessors: Porting Lib Accessors 3.1.0-fdrf.4+1.21.1
			porting_lib_base: Porting Lib Base 3.1.0-fdrf.4+1.21.1
			porting_lib_common: Porting Lib Common 3.1.0-fdrf.4+1.21.1
			porting_lib_conditions: Porting Lib Conditions 3.1.0-fdrf.4+1.21.1
			porting_lib_config: Porting Lib Config 3.1.0-fdrf.4+1.21.1
			porting_lib_core: Porting Lib Core 3.1.0-fdrf.4+1.21.1
			porting_lib_entity: Porting Lib Entity 3.1.0-fdrf.4+1.21.1
			porting_lib_extensions: Porting Lib Extensions 3.1.0-fdrf.4+1.21.1
			porting_lib_gui_utils: Porting Lib Gui Utils 3.1.0-fdrf.4+1.21.1
			porting_lib_item_abilities: Porting Lib Item Abilities 3.1.0-fdrf.4+1.21.1
			porting_lib_lazy_registration: Porting Lib Lazy Register 3.1.0-fdrf.4+1.21.1
			porting_lib_level_events: Porting Lib Level Events 3.1.0-fdrf.4+1.21.1
			porting_lib_loot: Porting Lib Loot 3.1.0-fdrf.4+1.21.1
			porting_lib_recipe_book_categories: Porting Lib Recipe Book Categories 3.1.0-fdrf.4+1.21.1
				mixinextras: MixinExtras 0.5.0-beta.3
			porting_lib_tags: Porting Lib Tags 3.0
			porting_lib_transfer: Porting Lib Transfer 3.1.0-fdrf.4+1.21.1
		ferritecore: FerriteCore 7.0.2-hotfix
		forgeconfigapiport: Forge Config API Port 21.1.2
		formations: Formations 1.0.2
		formationsnether: Formations Nether 1.0.5
		formationsoverworld: Formations Overworld 1.0.4
		friendsandfoes: Friends & Foes 3.0.6
		fsb-interop: FabricSkyBoxes Interop 1.4.0+mc1.21-build.54
		fwaystones: Fabric Waystones 3.3.4+mc1.21.1
		gobber2: Gobber2 2.10.28
		grindenchantments: Grind Enchantments 3.2.2+1.21-rc1
			codec-config-api: Codec config API 2.0.0+1.20.5-rc3
		immersiveui: ImmersiveUI 0.2.2
		infinities: Infinities 1.2+1.21
		iris: Iris 1.8.1+mc1.21.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		itemphysic: ItemPhysic 1.8.3
		jamlib: JamLib 1.0.11+1.21
		java: OpenJDK 64-Bit Server VM 23
		kiwi: Kiwi Library 15.1.2+fabric
		lambdynlights: LambDynamicLights 3.1.4+1.21.1
			pride: Pride Lib 1.2.1+1.21
			spruceui: SpruceUI 5.1.0+1.21
		lazydfu: LazyDFU 4.1
		lighty: Lighty 3.0.0-beta.7
		lithium: Lithium 0.14.3-snapshot+mc1.21.1-build.92
		lithostitched: Lithostitched 1.3.4
		lolmsv: More Shield Variants 1.2.2
		lootbeams: LootBeams 2.9.1-mc1.21-.1
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		maxhealthfix: MaxHealthFix 21.1.4
		mc-258859: MC-258859 1.0
		mcpitanlib: MCPitanLib 2.5.2-1.21-fabric
			compatdatapacks76: CompatDatapacks 1.0.10.210-fabric
		minecraft: Minecraft 1.21.1
		mo_glass: Mo Glass 1.10-MC1.21.1
		modernfix: ModernFix 5.19.3+mc1.21.1
		modmenu: Mod Menu 11.0.2
			placeholder-api: Placeholder API 2.4.0-pre.2+1.21
		moonfabric: moonfabric mod 1.21-1.3.9
		moonlight: Moonlight Lib 1.21-2.17.9
		more_gems: More Gems 1.7.19
		moreculling: More Culling 1.0.1
			conditional-mixin: conditional mixin 0.6.3
			mixinsquared: MixinSquared 0.2.0
		mr_blood_moon: Horde Nights 1.1.3
		mr_dungeons: Dungeons+ 1.9.0b
		mr_katters_structures: Katters Structures 2.1
		mr_lukis_grandcapitals: Luki's Grand Capitals 1.1.1
		mr_nofun_dnt: NoFun DnT 1-v1.0
		mr_vanilla_fireflies: Vanilla Fireflies 3.1
		mru: Mineblock's Repeated Utilities 1.0.4+1.21+fabric
		mythicmetals: Mythic Metals 0.20.2+1.21
			additionalentityattributes: Additional Entity Attributes 1.8.0+1.21
			common-protection-api: Common Protection API 1.0.0
		noisium: Noisium 2.3.0+mc1.21-1.21.1
		octolib: OctoLib 0.4.2
			org_yaml_snakeyaml: snakeyaml 2.2
		owo: oωo 0.12.15+1.21
			io_wispforest_endec: endec 0.1.5
			io_wispforest_endec_gson: gson 0.1.3
			io_wispforest_endec_jankson: jankson 0.1.3
			io_wispforest_endec_netty: netty 0.1.2
		particletweaks: Particle Tweaks 2.0-mc1.21.1
		patchouli: Patchouli 1.21-87-FABRIC
			fiber: fiber 0.23.0-2
		philipsruins: Philip`s Ruins 1.21.1
		pickupnotifier: Pick Up Notifier 21.1.0
		polytone: Polytone 1.21-2.5.12
		presencefootsteps: Presence Footsteps 1.10.2+1.21
			kirin: Kirin UI 1.20.0+1.21
		prickle: PrickleMC 21.1.6
		puzzle: Puzzle 2.0.1
			midnightlib: MidnightLib 1.6.3
		puzzleslib: Puzzles Lib 21.1.22
		random_ring: Random Ring 1.4.9
		reborncore: Reborn Core 5.11.11
			team_reborn_energy: Energy 4.1.0
		reeses-sodium-options: Reese's Sodium Options 1.8.0+mc1.21.3
		repurposed_structures: Repurposed Structures 7.5.12+1.21.1-fabric
		rightclickharvest: Right Click Harvest 4.3.1+1.21
		roughlyenoughitems: Roughly Enough Items 16.0.788
			error_notifier: Error Notifier 1.0.11
		sawmill: Universal Sawmill 1.21-1.5.10
		scalablelux: ScalableLux 0.1.0+fabric.26c6e72
		seasonhud: SeasonHUD 1.11.5
		seasons: Fabric Seasons 2.4.2-BETA+1.21
		seasonsextras: Fabric Seasons: Extras 1.3.2-BETA+1.21
		seasonsterralithcompat: Fabric Seasons: Terralith Compat 1.0-2.3.7
		simple_copper_pipes: Simple Copper Pipes 2.0.3
			frozenlib: FrozenLib 1.9.3-mc1.21.1
		simplemod: SimpleMod 1.21.1
		slimyfloor: Slimy Floor 1.21-1.3.2
		snowrealmagic: Snow! Real Magic! 11.0.13+fabric
		snowundertrees: Snow Under Trees 2.5.4+1.21.1
		snowyspirit: Snowy Spirit 1.21.1-3.0.15
		sodium: Sodium 0.6.2+mc1.21.1
		sound_physics_remastered: Sound Physics Remastered 1.21.1-1.4.6
		sounds: Sounds 2.2.1+1.21+fabric
		sprintindicator: Sprint Indicator 1.5.0
		storagedelight: Storage Delight 24.9.11-1.21-fabric
		structory: Structory 1.3.7
		structory_towers: Structory: Towers 1.0.9
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.8
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.17+c
		supplementaries: Supplementaries 1.21-3.0.25-beta
		taxfreelevels: Tax Free Levels 1.3.12
		techreborn: Tech Reborn 5.11.11
		terralith: Terralith 2.5.6
		tinycoal: TinyCoal 1.0.3
		toms_storage: Tom's Simple Storage Mod 2.0.9
		travelersbackpack: Traveler's Backpack 10.1.3
		trinkets: Trinkets 3.10.0
		villagehealthcare: Village Healthcare 1.1.0
		visuality: Visuality 0.7.7+1.21
		wthit: wthit 12.4.2
		xaerominimap: Xaero's Minimap 24.6.1
		xaeroworldmap: Xaero's World Map 1.39.0
		yet_another_config_lib_v3: YetAnotherConfigLib 3.6.1+1.21-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		yungsapi: YUNG's API 1.21.1-Fabric-5.1.3
			org_javassist_javassist: javassist 3.29.2-GA
			org_reflections_reflections: reflections 0.10.2
		yungsbridges: YUNG's Bridges 1.21.1-Fabric-5.1.1
		yungsextras: YUNG's Extras 1.21.1-Fabric-5.1.1

### Logs

https://pastebin.com/MPEzTJmZ

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by ChrysanthCow** [comment] 2024-12-03 23:28
Duplicate of #118.
Update to 2.2.5.

**Closed as completed by ChrysanthCow** 2024-12-03 23:28 UTC

**Comment by Cr4fTJuNkiE** [comment] 2024-12-03 23:30
Awesome. Thank you!
