### ISSUE TITLE
Errors in registry causing disconnect from protocol error

### ISSUE THREAD

**Issue by CoinMirage** [MehVahdJukaar/FarmersDelightRefabricated#95] opened 2024-09-30 09:45 UTC
### Minecraft version

1.21.1

### Farmer's Delight version

2.1.9

### Fabric Loader version

0.16.5

### Fabric API version

0.105.0+1.21.1

### Description

so whenever i try to connect to my own server i end up getting kicked for too many suspicious packages seemingly caused by the enchantments failing in some way.

### Steps to reproduce

running farmer's delight on a fabric server

### Mod list

fabric api
minecord
Yungs Api
repurposed structures
towns and towers
critsellib
midnightlib
bettersleep
farmers delight refabricated
architectury
moonlight
Sky villages

### Logs

https://mclo.gs/IaCrH1q

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by Poopooracoocoo** [comment] 2024-10-01 10:53
You need a lot of those mods on your client.

**Comment by CoinMirage** [comment] 2024-10-05 18:25
> You need a lot of those mods on your client.

yeah it was happening with some other mods too until i just added stuff like midnightlib on the client side, silly me as a first time mod user!

**Comment by Poopooracoocoo** [comment] 2024-10-05 18:42
You should close this issue as it's a user error and not a bug.

**Closed as not planned** 2024-11-09 02:23 UTC
